### ISSUE TITLE
any demo or screenshot?

### ISSUE THREAD

**Issue by fastfading** [dgengin/DGEngine#1]
Hi  I just notice your work. 
What is the difference from freediablo?
Any video demo or screenshot could show us how the project is going.
Or at least give us a discription .
Thanks

**Comment by ghost** [comment]
Hi,

If you're familiar with the original game, What's done is everything up to the town level, except all the game logic (items, enemies, spells). But you can browse town, load level 1 (right click on town level), talk to the town players, etc.

The best way to see what's done it to try it yourself.

The first 7-10 seconds of this video is pretty much what's done right now:
https://www.youtube.com/watch?v=pM7T_PdAJdE

I have updated the wiki / release with instructions on how to use the original game's beta files, in case you don't have those. Some things don't load but it's mostly the same.

**Comment by mewmew** [comment]
This issue can probably be closed as the README now contains screenshots, and https://github.com/dgengin/DGEngine/issues/2 contains further video demo/screenshots.
