### ISSUE TITLE
Mismatch of tile IDs when using FLARE resources

### ISSUE THREAD

**Issue by mewmew** [dgengin/DGEngine#19]
For of all, hats off to the work you've put into making the game engine generic enough to work with FLARE resources as well! It's really great to follow the progress and evolution of the DGEngine.

I tried to use the FLARE resources from fantasycore by cloning https://github.com/clintbellanger/flare-game and creating a zip file named `fantasycore.zip` containing the contents of the directory `flare-game/mods/fantasycore`.

```bash
u@x220 ~/D/d/D/f/m/fantasycore> zip -r ../fantasycore.zip *
  adding: animations/ (stored 0%)
  adding: animations/powers/ (stored 0%)
  adding: animations/powers/stone.txt (deflated 20%)
  adding: animations/powers/plasmaball.txt (deflated 37%)
  adding: animations/powers/cleave.txt (deflated 62%)
  adding: animations/powers/spark_red.txt (deflated 42%)
  adding: animations/powers/spark_red_loop.txt (deflated 40%)
  adding: animations/powers/icicle.txt (deflated 60%)
  adding: animations/powers/fireball.txt (deflated 57%)
  adding: animations/powers/thunderstrike.txt (deflated 21%)
  adding: animations/powers/quake.txt (deflated 58%)
  adding: animations/powers/shield.txt (deflated 19%)
  adding: animations/powers/channel.txt (deflated 56%)
  adding: animations/powers/spark_blue.txt (deflated 42%)
  adding: animations/powers/throw_axe.txt (deflated 63%)
  adding: animations/powers/lightning.txt (deflated 63%)
```

The I tried to place the `fantasycore.zip` file in the root directory of the DGEngine repository (alongside DIABDAT.MPQ), and it worked well to start DGEngine with `./DGEngine ./gamefilesflare`, the menus showed up well and the sound effects and background music works.

However, upon starting a new game, the town is rendered very strangely. It seems like the tile IDs have been mixed up? For reference, I'm using rev clintbellanger/flare-game@0b7ad2e7fdaf9e3d6459538de1aff948b0d7cfdb. I've been using rev b68b61f8195c689fed2f80645f467ab1a5bacd3b of DGEngine.

![dgengine_using_flare](https://user-images.githubusercontent.com/1414531/37244466-b16225ac-2489-11e8-94f4-8266b8e5d89f.png)

Does it work locally for you, if so with what revision of the game assets from the `flare-game` repo?

Cheers,
/u

**Comment by ghost** [comment]
Hi. Yes, it appears they updated all the images 9 days ago.
Use 0.19: https://github.com/clintbellanger/flare-game/tree/branch0.19

**Comment by mewmew** [comment]
> Hi. Yes, it appears they updated all the images 9 days ago.

I see. I think this is in preparation for the 1.0 release, which is dated for tomorrow (12th of Mars).

>  Use 0.19: https://github.com/clintbellanger/flare-game/tree/branch0.19

I'll give it a shot.

**Comment by mewmew** [comment]
This time it worked! It's a really amazing job you've done getting the FLARE assets to work on the same engine. Still some minor glitches as I'm sure you are aware, but these will be sorted in time.

Happy coding!
/u

![dgengine_flare_v0 19](https://user-images.githubusercontent.com/1414531/37257863-08f37cea-256f-11e8-97a6-696c6a3bd007.png)
