### ISSUE TITLE
Loading... message never fades

### ISSUE THREAD

**Issue by mewmew** [dgengin/DGEngine#25]
If you start a new game, and enter the game menu to press Load, the "Loading..." text is displayed, and this text never goes away. You can still walk around in town and the game works well, just that the text never fades.

![2019-05-15-205141_800x600_scrot](https://user-images.githubusercontent.com/1414531/57773660-775bb300-7753-11e9-8217-9142489b1d40.png)

**Comment by ghost** [comment]
I changed the gamefiles related to messages and forgot to test the game load. It's fixed in this last commit.
