### ISSUE TITLE
Collision detection, it is possible to walk through the cathedral

### ISSUE THREAD

**Issue by mewmew** [dgengin/DGEngine#9]
Collision detection, it is possible to walk through the cathedral

![Collision detection, passing through the cathedral](https://media.giphy.com/media/3oz8xHeeq0W4XZTu7u/giphy.gif)

**Comment by ghost** [comment]
I knew about this. I just let it be that way as it wasn't critical.

I just fixed this on 8c320b0. The reason why this happened was because I added all possible 8 movements to the search algorithm, and you can't add diagonal movements if the corresponding straight ones are not passable.

**Comment by mewmew** [comment]
> I just fixed this on 8c320b0.

Lovely. Closing this issue for now as it has been resolved in the aforementioned commit. Will re-open if I notice any further issues.
